# -*- coding: utf-8 -*-
"""FirstpositiveKloop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m61pYZpmS5jDw6XDjiFHRG1Le5hx1ZQd
"""

def sum_of_integers(k):
    p = 0
    for i in range(1, k + 1):
        p += i
        print(f"After adding {i}, the cumulative sum is {p}")
    return p

# Example usage:
k = 5
result = sum_of_integers(k)
print("Final sum of first", k, "positive integers is:", result)