# -*- coding: utf-8 -*-
"""Insertion_Sort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o_PnyG4EV5eybsn0xX8R1ROTI4pEwKP5
"""

def insertionSort(arr):
    # Traverse through 1 to len(arr)
    for i in range(1, len(arr)):
        key = arr[i]  # The current element to be placed in the sorted portion
        j = i - 1

        # Move elements of arr[0..i-1], that are greater than key, to one position ahead
        # of their current position
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key

        # Print the array after each iteration
        print(f"Iteration {i}: {arr}")

# Driver code to test the insertion sort implementation
arr = [34, 25, 12, 22, 11, 64, 90]
print("Original array:", arr)
insertionSort(arr)
print("Sorted array:", arr)