# -*- coding: utf-8 -*-
"""LinearSearch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-KeRskNpXOE7chr-JD3_fWxStKjLYshl
"""

def linear_search(arr, target):
    # Loop through each element in the array

    for i in range(len(arr)):
        #Print the current state of the array and the current element being compared
        print(f"Iteration {i + 1}: Checking element {arr[i]}")

        # Check if the current element is equal to the target
        if arr[i] == target:
            print(f"Target {target} found at index {i}")
            return i # Return the index if found

    print(f"Target {target} not found in the array")
    return -1 # Return -1 if not found

# Example usage
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
target = 7


result = linear_search(arr, target)

if result == -1:
    print("Element not found in the array")

print(f"Result: {result}")